//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Absa.DateAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AbsaDataModelEntities : DbContext
    {
        public AbsaDataModelEntities()
            : base("name=AbsaDataModelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataLookUp> DataLookUps { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DepartmentAudit> DepartmentAudits { get; set; }
        public virtual DbSet<LookUpName> LookUpNames { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersAudit> UsersAudits { get; set; }
    }
}
