//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Absa.DateAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessUnitAudit
    {
        public int BusinessUnitAuditID { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public string BusinessUnitName { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> DateLogged { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdateOn { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
    }
}
