//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Absa.DateAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResilienceTrack
    {
        public int ID { get; set; }
        public string ApplicationID { get; set; }
        public string ApplicationName { get; set; }
        public string NameOnSnow { get; set; }
        public string HeadOfTechnology { get; set; }
        public string ApplicatioOwner { get; set; }
        public string ServiceManager { get; set; }
        public Nullable<long> Tiering { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
    
        public virtual BusinessUnit BusinessUnit { get; set; }
    }
}
