//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Absa.DateAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResilienceTrackAudit
    {
        public Nullable<int> ResilienceTrackID { get; set; }
        public string FieldName { get; set; }
        public Nullable<System.DateTime> DateLogged { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> BusinessUnitId { get; set; }
        public Nullable<int> StatusId { get; set; }
    }
}
